// Ayu Dark theme colors (Official)
export const ayuDarkTheme = {
  'code[class*="language-"]': {
    color: '#d0d0d0',
    background: '#0f1419',
    fontFamily: "'Monaco', 'Consolas', 'Courier New', monospace",
    fontSize: '0.75rem',
    lineHeight: '1.4',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#d0d0d0',
    background: '#0f1419',
    fontFamily: "'Monaco', 'Consolas', 'Courier New', monospace",
    fontSize: '0.75rem',
    lineHeight: '1.4',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '0',
    margin: '0',
    overflow: 'auto',
  },
  'comment': { color: '#828C99', fontStyle: 'italic' },
  'prolog': { color: '#828C99' },
  'doctype': { color: '#828C99' },
  'cdata': { color: '#828C99' },
  'punctuation': { color: '#d0d0d0' },
  'property': { color: '#FFB454' },
  'tag': { color: '#FF8F40' },
  'boolean': { color: '#FF8F40' },
  'number': { color: '#FFCC66' },
  'constant': { color: '#FF8F40' },
  'symbol': { color: '#FF8F40' },
  'deleted': { color: '#FF3333' },
  'selector': { color: '#FF8F40' },
  'attr-name': { color: '#FFB454' },
  'string': { color: '#A8D84D' },
  'char': { color: '#A8D84D' },
  'builtin': { color: '#FF8F40' },
  'inserted': { color: '#A8D84D' },
  'operator': { color: '#FF8F40' },
  'entity': { color: '#FFB454' },
  'url': { color: '#A8D84D' },
  '.language-css .token.string': { color: '#A8D84D' },
  '.style .token.string': { color: '#A8D84D' },
  'variable': { color: '#39BAE6' },
  'atrule': { color: '#FF8F40' },
  'attr-value': { color: '#A8D84D' },
  'function': { color: '#FFB454' },
  'function-variable': { color: '#FFB454' },
  'method': { color: '#FFB454' },
  'class-name': { color: '#59C2FF' },
  'keyword': { color: '#FF8F40' },
  'control': { color: '#FF8F40' },
  'directive': { color: '#FF8F40' },
  'module': { color: '#FF8F40' },
  'unit': { color: '#FF8F40' },
  'statement': { color: '#FF8F40' },
  'regex': { color: '#95E6CB' },
  'important': { color: '#FF8F40', fontWeight: 'bold' },
  'parameter': { color: '#39BAE6' },
  'this': { color: '#FF8F40', fontStyle: 'italic' },
  'self': { color: '#FF8F40', fontWeight: 'bold', fontStyle: 'italic' },
  'cls': { color: '#FF8F40', fontWeight: 'bold', fontStyle: 'italic' },
  'function-call': { color: '#FFB454' },
  'maybe-class-name': { color: '#59C2FF' },
  'namespace': { color: '#59C2FF' },
  'decorator': { color: '#E6B673' },
  'annotation': { color: '#E6B673' },
  'bold': { fontWeight: 'bold' },
  'italic': { fontStyle: 'italic' },
};

// VS Code Dark+ theme colors (Default)
export const vsCodeDarkTheme = {
  'code[class*="language-"]': {
    color: '#D4D4D4',
    background: '#1E1E1E',
    fontFamily: "'Monaco', 'Consolas', 'Courier New', monospace",
    fontSize: '0.75rem',
    lineHeight: '1.4',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#D4D4D4',
    background: '#1E1E1E',
    fontFamily: "'Monaco', 'Consolas', 'Courier New', monospace",
    fontSize: '0.75rem',
    lineHeight: '1.4',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '0',
    margin: '0',
    overflow: 'auto',
  },
  'comment': { color: '#6A9955', fontStyle: 'italic' },
  'prolog': { color: '#6A9955' },
  'doctype': { color: '#6A9955' },
  'cdata': { color: '#6A9955' },
  'punctuation': { color: '#D4D4D4' },
  'property': { color: '#9CDCFE' },
  'tag': { color: '#569CD6' },
  'boolean': { color: '#569CD6' },
  'number': { color: '#B5CEA8' },
  'constant': { color: '#4FC1FF' },
  'symbol': { color: '#4FC1FF' },
  'deleted': { color: '#F44747' },
  'selector': { color: '#D7BA7D' },
  'attr-name': { color: '#9CDCFE' },
  'string': { color: '#CE9178' },
  'char': { color: '#CE9178' },
  'builtin': { color: '#4EC9B0' },
  'inserted': { color: '#B5CEA8' },
  'operator': { color: '#D4D4D4' },
  'entity': { color: '#DCDCAA' },
  'url': { color: '#CE9178' },
  '.language-css .token.string': { color: '#CE9178' },
  '.style .token.string': { color: '#CE9178' },
  'variable': { color: '#9CDCFE' },
  'atrule': { color: '#C586C0' },
  'attr-value': { color: '#CE9178' },
  'function': { color: '#DCDCAA' },
  'function-variable': { color: '#DCDCAA' },
  'method': { color: '#DCDCAA' },
  'class-name': { color: '#4EC9B0' },
  'keyword': { color: '#569CD6' },
  'control': { color: '#C586C0' },
  'directive': { color: '#C586C0' },
  'module': { color: '#C586C0' },
  'unit': { color: '#B5CEA8' },
  'statement': { color: '#C586C0' },
  'regex': { color: '#D16969' },
  'important': { color: '#569CD6', fontWeight: 'bold' },
  'parameter': { color: '#9CDCFE' },
  'this': { color: '#569CD6', fontStyle: 'italic' },
  'self': { color: '#569CD6', fontWeight: 'bold', fontStyle: 'italic' },
  'cls': { color: '#569CD6', fontWeight: 'bold', fontStyle: 'italic' },
  'function-call': { color: '#DCDCAA' },
  'maybe-class-name': { color: '#4EC9B0' },
  'namespace': { color: '#4EC9B0' },
  'decorator': { color: '#4EC9B0' },
  'annotation': { color: '#4EC9B0' },
  'bold': { fontWeight: 'bold' },
  'italic': { fontStyle: 'italic' },
};

// GitHub Light theme colors (Comfortable light scheme)
export const githubLightTheme = {
  'code[class*="language-"]': {
    color: '#24292f',
    background: '#ffffff',
    fontFamily: "'Monaco', 'Consolas', 'Courier New', monospace",
    fontSize: '0.75rem',
    lineHeight: '1.4',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#24292f',
    background: '#ffffff',
    fontFamily: "'Monaco', 'Consolas', 'Courier New', monospace",
    fontSize: '0.75rem',
    lineHeight: '1.4',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '0',
    margin: '0',
    overflow: 'auto',
  },
  'comment': { color: '#6e7781', fontStyle: 'italic' },
  'prolog': { color: '#6e7781' },
  'doctype': { color: '#6e7781' },
  'cdata': { color: '#6e7781' },
  'punctuation': { color: '#24292f' },
  'property': { color: '#0550ae' },
  'tag': { color: '#116329' },
  'boolean': { color: '#0550ae' },
  'number': { color: '#0550ae' },
  'constant': { color: '#0550ae' },
  'symbol': { color: '#0550ae' },
  'deleted': { color: '#cf222e' },
  'selector': { color: '#6f42c1' },
  'attr-name': { color: '#0550ae' },
  'string': { color: '#0a3069' },
  'char': { color: '#0a3069' },
  'builtin': { color: '#953800' },
  'inserted': { color: '#116329' },
  'operator': { color: '#cf222e' },
  'entity': { color: '#8250df' },
  'url': { color: '#0a3069' },
  '.language-css .token.string': { color: '#0a3069' },
  '.style .token.string': { color: '#0a3069' },
  'variable': { color: '#953800' },
  'atrule': { color: '#0550ae' },
  'attr-value': { color: '#0a3069' },
  'function': { color: '#8250df' },
  'function-variable': { color: '#8250df' },
  'method': { color: '#8250df' },
  'class-name': { color: '#953800' },
  'keyword': { color: '#cf222e' },
  'control': { color: '#cf222e' },
  'directive': { color: '#cf222e' },
  'module': { color: '#cf222e' },
  'unit': { color: '#0550ae' },
  'statement': { color: '#cf222e' },
  'regex': { color: '#116329' },
  'important': { color: '#cf222e', fontWeight: 'bold' },
  'parameter': { color: '#24292f' },
  'this': { color: '#cf222e', fontStyle: 'italic' },
  'self': { color: '#cf222e', fontWeight: 'bold', fontStyle: 'italic' },
  'cls': { color: '#cf222e', fontWeight: 'bold', fontStyle: 'italic' },
  'function-call': { color: '#8250df' },
  'maybe-class-name': { color: '#953800' },
  'namespace': { color: '#953800' },
  'decorator': { color: '#8250df' },
  'annotation': { color: '#8250df' },
  'bold': { fontWeight: 'bold' },
  'italic': { fontStyle: 'italic' },
};
